[selenium]
headless = false
time_to_wait = 15
time_to_refresh = 3600
video_limit = 50
duplicate_limit = 50

[redis]
url = "redis://:1234@redis:6379/0"

[nats]
url = "nats://nats:4222"

[storage]
access_key = ""
secret_key = ""
bucket = ""
