services:
   reviews-scraper:
      container_name: reviews
      depends_on:
         - redis
      restart: always
      build:
         context: ../
         dockerfile: ./.actor/Dockerfile
      ports:
         - '7900:7900'
      volumes:
         - '../:/app'
         - '../config/prod_config.toml:/app/config/dev_config.toml:ro'
      environment:
         - CONFIG_ENV=dev
         - PYTHONUNBUFFERED=1
   redis:
      container_name: redis
      image: 'bitnami/redis:7.2'
      restart: always
      environment:
         - 'REDIS_PORT_NUMBER=${REDIS_PORT:-6379}'
         - 'REDIS_PASSWORD=${REDIS_PASSWORD:-1234}'
