services:
   reviews-scraper:
      container_name: reviews
      depends_on:
         - redis
         - nats
      restart: always
      command: poetry run python manage.py reviews
      build:
         context: ../
         dockerfile: ./docker/Dockerfile
      ports:
         - '7900:7900'
      volumes:
         - '../scraper:/app/scraper:ro'
         - '../scripts:/app/scripts:ro'
         - '../storage:/app/storage:rw'
         - '../config/prod_config.toml:/app/config/dev_config.toml:ro'
      environment:
         - CONFIG_ENV=dev
   redis:
      container_name: redis
      image: 'bitnami/redis:7.2'
      restart: always
      environment:
         - 'REDIS_PORT_NUMBER=${REDIS_PORT:-6379}'
         - 'REDIS_PASSWORD=${REDIS_PASSWORD:-1234}'
   nats:
      container_name: nats
      image: 'nats:2.10'
      restart: on-failure
      environment:
         - 'NATS_PORT=${NATS_PORT:-4222}'
         - 'NATS_CLUSTER_PORT=${NATS_CLUSTER_PORT:-4248}'
         - 'NATS_HTTP_PORT=${NATS_HTTP_PORT:-8222}'
         - 'NATS_CLUSTER_USER=${NATS_CLUSTER_USER:-nats}'
         - 'NATS_CLUSTER_PASSWORD=${NATS_CLUSTER_PASSWORD:-1234}'
